Pure_Beurre/Pure_Beurre/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500

handler404 = "substitute.views.handler404"
handler500 = "substitute.views.handler500"
urlpatterns = [
    path('substitute/', include('substitute.urls')),
    path('admin/', admin.site.urls),
    path('substitute/', include('django.contrib.auth.urls')),
]

Pure_Beurre/substitute/urls.py
""" This module handle the urls of the application.
 It precise the format to use, the views function to call and a name.  """
from django.urls import path, re_path


from . import views

app_name = "substitute"
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.homepage, name='home'),
    path('search/product=<str:product>', views.search, name='search'),
    path('aliment/S=<str:s_id>&P=<str:p_id>&U=<str:u_id>/', views.aliment, name='aliment'),
    path('save/P=<str:p_id>&S=<str:s_id>&U=<str:u_id>/', views.save, name='save'),
    path('account/', views.account, name='account'),
    path('historic/', views.historic, name='historic'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mentions/', views.mentions, name='mentions'),
    path('activate/uidb64=<str:uidb64>&token=<str:token>/', views.activate, name='activate'),
]

Pure_Beurre/substitute/models.py
""" This module is listing all the models
 which are needed for the application Web Site 'substitute'. """
from django.db import models
from django.contrib.auth.models import User
# -*- coding: utf-8 -*-

# Create your models here.


class Text(models.Model):
    """ This model is used for displaying text into two templates :
        home.html and mentions.html."""
    language = models.CharField(max_length=2, null=True)
    mentions_title = models.CharField(max_length=1000, null=True)
    mentions_id_fn = models.CharField(max_length=1000, null=True)
    mentions_id_ln = models.CharField(max_length=1000, null=True)
    mentions_id_ph = models.CharField(max_length=1000, null=True)
    mentions_id_m = models.CharField(max_length=1000, null=True)
    mentions_id_pn = models.CharField(max_length=1000, null=True)
    mentions_id_s = models.CharField(max_length=1000, null=True)
    mentions_a_rcs = models.CharField(max_length=1000, null=True)
    mentions_a_fn = models.CharField(max_length=1000, null=True)
    mentions_a_cgv = models.CharField(max_length=1000, null=True)
    mentions_cookies = models.CharField(max_length=1000, null=True)
    home_s = models.CharField(max_length=1000, null=True)
    home_c = models.CharField(max_length=1000, null=True)
    home_bm = models.CharField(max_length=1000, null=True)


class Customer(models.Model):
    """ This model is a special user model. It is especially used for identify a record's owner """
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        """ This method displaying the user's name when a customer model instance is called. """
        return self.user.username


class Category(models.Model):
    """ This model's describing a product's category.
        It is linked to Aliment model by a 'many to many relationship'."""
    id_name = models.CharField(max_length=500, null=True)
    name = models.CharField(max_length=500, null=True)
    url = models.URLField(max_length=500, null=True)

    def __str__(self):
        """ This method displaying the category's name when the model instance is called. """
        return self.name


class Aliment(models.Model):
    """ This model's describing a product.
        It is linked to Category model by a 'many to many relationship'."""
    name = models.CharField(max_length=500, null=True)
    tag = models.ManyToManyField(Category)
    category = models.CharField(max_length=500, null=True)
    brand = models.CharField(max_length=500, null=True)
    nutriscore = models.CharField(max_length=1, null=True)

    image_nutriments = models.URLField(max_length=500, null=True)
    energy_kj = models.CharField(max_length=100, null=True)
    energy_kj_unit = models.CharField(max_length=100, null=True)
    energy_kcal = models.CharField(max_length=100, null=True)
    energy_kcal_unit = models.CharField(max_length=100, null=True)

    store = models.CharField(max_length=500, null=True)
    purchase_places = models.CharField(max_length=500, null=True)
    url = models.URLField(max_length=500, null=True)
    url_image = models.URLField(max_length=500, null=True)

    def __str__(self):
        """ This method displaying the product's name when the model instance is called. """
        return self.name


class Historic(models.Model):
    """ This model's describing a historic record.
        A record is composed of its owner, a product and its substitute."""
    user = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE)
    aliment = models.ForeignKey(Aliment, related_name="aliment", null=True, on_delete=models.CASCADE)
    substitute = models.ForeignKey(Aliment,related_name="substitute", null=True, on_delete=models.CASCADE)

    def __str__(self):
        """ This method displaying the record's id when the model instance is called. """
        return str(self.id)

Pure_Beurre/substitute/forms.py
""" This module using the 'User' model and UserCreationForm format  to create new users """
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    """ This class inherits from UserCreationForm.
      However, its behaviour is based on models.User.
      So, the authentification is handled by Django."""
    class Meta:
        """ This class provides User model and edits username,
         email passwords."""
        model = User
        fields = ["username", "email", "password1", "password2"]

Pure_Beurre/substitute/views.py
""" This module handles all the views of the application. """
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User as usr
from django.contrib.auth import authenticate, login as lgi, logout as lgo
from django.contrib import messages
from pathlib import Path
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.db import IntegrityError

# Create your views here.
from .forms import CreateUserForm
from .operations import *
from .models import *
from .mail import *
from Pure_Beurre.settings import GMAP_KEY

BASE_DIR = Path(__file__).resolve().parent.parent


def handler404(request, exception=None):
    """ This function takes care of 404 errors.
     When a 404 error occurs, the '404.html' is displayed."""
    page = "acceuil"
    return render(request, "errors/404.html", {"data": page}, status=404)


def handler500(request, exception=None):
    """ This function takes care of 500 errors.
     When a 404 error occurs, the '500.html' is displayed."""
    page = "acceuil"
    return render(request, "errors/500.html", {"data": page}, status=500)


def index(request):
    """ This function is a shortcut-like view to the homepge view. """
    return homepage(request)


def search(request, product):
    """ This function is the twin view of homepage().
    It's called to handle the seek of products.
    It is composed of a error handler to secure the user entries."""
    if "browser_product" in request.POST:
        browser_product = request.POST.get("browser_product")
        print(browser_product)
        return redirect("/substitute/search/product={}".format(browser_product))
    text = get_text()
    context = {"text": text,
               "goal": "Trouvez un produit de substitution pour ceux que vous consommez tous les jours"}
    raw_data = secure_text(product)
    result_engine = DataSearch(raw_data)
    data = result_engine.big_data
    if len(data) == 0:
        msg = "Produit inconnu au bataillon !!! Veuillez reformuler votre saisie ou essayez un autre..."
        print("search len(data) : {}".format(request))
        messages.error(request, msg)
        return redirect("/substitute/home")
    found_aliment = next(reversed(data.items()))[1]
    context["product"] = found_aliment
    context["product_nutriscore"] = set_nutriscore_tag(found_aliment.nutriscore)
    context["results"] = data
    return render(request, "substitute/search.html", context)


def homepage(request):
    """ This function is the main view of the application. It's rendering the homepage 'home.html',
      where the user can search products or just read contents."""
    home_text = open_js_file(os.path.join(BASE_DIR, "substitute/static/substitute/json/text.json"))
    text = get_text()
    context = {"text": text,
               "goal": "Trouvez un produit de substitution pour ceux que vous consommez tous les jours",
               "version_tag": home_text["fr"]["browser"]["version"],
               "colette_story": home_text["fr"]["home"]["colette_story"],
               "remy_story": home_text["fr"]["home"]["remy_story"]}
    if request.method == "POST":
        if "browser_product" in request.POST:
            browser_product = request.POST.get("browser_product")
            print(browser_product)
            return redirect("/substitute/search/product={}".format(browser_product))
        if "product" in request.POST:
            product = request.POST.get("product")
            if is_entry_empty(product)["status"]:
                context["error_entry"] = is_entry_empty(product)["text"]
                print("search is_entry : {}".format(request))
                msg = context["error_entry"]
                messages.error(request, msg)
                return render(request, "substitute/home.html", context)
            return redirect("/substitute/search/product={}".format(product))
    return render(request, "substitute/home.html", context)


def save(request, p_id, s_id, u_id):
    """ This function is called to catch product,
     substitute and user id's before launch a record of swap. """
    if "browser_product" in request.POST:
        browser_product = request.POST.get("browser_product")
        print(browser_product)
        return redirect("/substitute/search/product={}".format(browser_product))
    context = {}
    p = Aliment.objects.get(id=p_id)
    s = Aliment.objects.get(id=s_id)
    u = User.objects.get(id=u_id)
    c = Customer.objects.get(user_id=u_id)
    record = DataSave(p, s, c)
    record.store_data()
    context["title"] = ["Aliment initial", "Aliment de substitution"]
    context["p"] = p
    context["s"] = s
    context["u"] = u
    context["p_nutriscore"] = set_nutriscore_tag(p.nutriscore)
    context["s_nutriscore"] = set_nutriscore_tag(s.nutriscore)
    return render(request, "substitute/save.html", context)


def aliment(request, p_id, s_id, u_id):
    """ This function is called to get more details on a product. """
    if "browser_product" in request.POST:
        browser_product = request.POST.get("browser_product")
        print(browser_product)
        return redirect("/substitute/search/product={}".format(browser_product))
    s_session = DataAliment(s_id)
    substitute = s_session.aliment

    substitute_stores = str(substitute.store)
    substitute_pp = str(substitute.purchase_places)
    substitute_stores = substitute_stores.split(", ")
    substitute_pp = substitute_pp.split(", ")
    gmap_markers = gmap_builder(substitute_stores, substitute_pp)
    gmap_average = average_location(gmap_markers)
    p_session = DataAliment(p_id)
    product = p_session.aliment
    substitute_nutrscore = set_nutriscore_tag(substitute.nutriscore)
    context = {"substitut": substitute,
               "substitut_nutriscore": substitute_nutrscore,
               "produit": product,
               "utilisateur_id": u_id,
               "gmap_key": GMAP_KEY,
               "stores": substitute_stores,
               "pps": substitute_pp,
               "lat": str(50.4462262),
               "lng": str(2.9444979),
               "gmap_markers": gmap_markers,
               "gmap_average": gmap_average
               }
    return render(request, "substitute/aliment.html", context)


def account(request):
    """ This function handles account user. """
    if "browser_product" in request.POST:
        browser_product = request.POST.get("browser_product")
        print(browser_product)
        return redirect("/substitute/search/product={}".format(browser_product))
    context = {}
    c = Customer.objects.get(user_id=request.user.id)
    the_historic = get_historic(c)
    context["salutation"] = "SALUT"
    return render(request, "substitute/account.html", context)


def historic(request):
    """ This function handles historic user. """
    if "browser_product" in request.POST:
        browser_product = request.POST.get("browser_product")
        print(browser_product)
        return redirect("/substitute/search/product={}".format(browser_product))
    context = {}
    c = Customer.objects.get(user_id=request.user.id)
    the_historic = get_historic(c)
    if len(the_historic) == 0:
        context["empty"] = "Votre historique est vide"
    context["history"] = the_historic
    context["titre_aliment"] = "ALIMENT"
    context["titre_substitut"] = "SUBSTITUT"
    context["salutation"] = "BIENVENUE"
    context["mail"] = "utilisateur@purebeurre.com"
    return render(request, "substitute/historic.html", context)


def login(request):
    """ This function drives the user
     to the login page or the account page,
      depending on authentication status. """
    if "browser_product" in request.POST:
        browser_product = request.POST.get("browser_product")
        print(browser_product)
        return redirect("/substitute/search/product={}".format(browser_product))
    if request.user.is_authenticated:
        return redirect("/substitute/account")
    else:
        if request.method == "POST":
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                lgi(request, user)
                return redirect("/substitute/account")
            else:
                messages.info(request, "Les informations saisies sont incorrectes !")
        context = {}
        return render(request, "registration/login.html", context)


def logout(request):
    """ This function redirects
     user to homepage() after log out. """
    lgo(request)
    return redirect("/substitute/home")


def register(request):
    """ This function drives the user
     to the register page or the account page,
    depending on authentication status. """
    if "browser_product" in request.POST:
        browser_product = request.POST.get("browser_product")
        print(browser_product)
        return redirect("/substitute/search/product={}".format(browser_product))
    if request.user.is_authenticated:
        return redirect("/substitute/account")
    else:
        form = CreateUserForm()
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.cleaned_data.get("username")
                user_mail = form.cleaned_data.get("email")
                user_data = form.save(commit=False)
                send_confirmation(request, user_data, user_mail)
                return render(request, "registration/validation.html")
            else:
                print("Les informations saisies sont incorrectes !")
                messages.info(request, "Les informations saisies sont incorrectes !")
        context = {"form": form}
        return render(request, "registration/register.html", context)

Pure_Beurre/substitute/templates/substitute/aliment.html
{% extends 'substitute/base.html'%}
{% block heart %}
{% load static %}
<style type="text/css">
    #aliment-area
    {
        background: url('{{ substitut.url_image}}');
        background-position: center;
    }

</style>
<div class="container-fluid" id="aliment-area">
    <div class="row">
        <div class="col-12"><br/></div>
        <div class="col-12 h1 d-flex justify-content-center" >
            <a href="{{ substitut.url }}" class="col-3 btn btn-lg btn-create-account btn-block text-uppercase bg-butter "> {{ substitut.name }}</a>
        </div>
        <div class="col-12"><br/></div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12"> <br/></div>
                <div class="col-12 h2">
                    <img src="{{ substitut.url_image}}">
                    <a class="chocolate-text " style="text-decoration:none" href="{% url 'substitute:aliment' s_id=substitut.id p_id=produit.id u_id=utilisateur_id  %}"></a>
                </div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text">Marque : {{ substitut.brand|upper }}</div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text">Produit : {{ substitut.name }}</div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text">Magasin(s) : {{ substitut.store }}</div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text">Lieu(x) de vente : {{ substitut.purchase_places }}</div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text"> </div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text"> </div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text"> </div>
        <div class="col-12 h2 d-flex justify-content-center chocolate-text"> </div>
        <div class="col-6 d-flex justify-content-center underline-text h3">Nutriscore abCde</div>
        <div class="col-6 d-flex justify-content-center underline-text h3">Repères nutritionnels pour 100g</div>
        <div class="col-6 d-flex justify-content-center  h3" style="align-items:center">
            <div class="col-6 d-flex justify-content-center  h3" style="align-items:center">
                <img src="{{ substitut_nutriscore }}" alt="Nutriscore"></div>
            </div>
            <div class="col-6 d-flex justify-content-center h3">
                <div class="col-12"><img src="{{ substitut.image_nutriments }}"></div>
            </div>
            <div class="col-6 d-flex justify-content-center h3"></div>
            <div class="col-6 d-flex justify-content-center underline-text h3">Energie</div>
            <div class="col-6 d-flex justify-content-center h3"></div>
            <div class="col-6 d-flex justify-content-center h3">{{ substitut.energy_kj }} {{ substitut.energy_kj_unit }} <br/>{{ substitut.energy_kcal }} {{ substitut.energy_kcal_unit }}</div>
            <div class="col-12"> <br/></div>
<div class="container-fluid">
    <div class="row" id="gmap">
        <div class="col-12">Les Points de ventes</div>
        <div class="col-12"></div>
        <div class="col-4">
            <div><img src="{% static 'substitute/png/shop.png' %}" height="200" width="200" alt="Shop"></div>
        </div>
        <div class="col-4 border" id="gmap-square">
            <div id="gmap-window"></div>
        </div>
        <div class="col-4">
            <div><img src="{% static 'substitute/png/countries.png' %}" height="200" width="200" alt="Countries"></div>
        </div>
    </div>
</div>
            <div class="col-12"> <br/></div>
            <div class="col-12 h3">
                <form method="POST">
                    {% csrf_token %}
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'substitute:save' p_id=produit.id s_id=substitut.id u_id=utilisateur_id %}">
                        <img src="{% static 'substitute/png/blue_save.png' %}" height="200" width="200" alt="Disquette - sauvegarde">
                        <div class="col-12 h3">Sauvegarder</div>
                    </a>
                    {% else %}
                    <a href="{% url 'substitute:login' %}">
                        <img src="{% static 'substitute/png/blue_save.png' %}" height="200" width="200" alt="Disquette - sauvegarde">
                        <div class="col-12 h3">Sauvegarder</div>
                    </a>
                    {% endif %}
                </form>
            </div>
            <form class="col-12 d-flex justify-content-center">
                <a href="{{ substitut.url }}" class="col-3 btn btn-lg btn-create-account btn-block text-uppercase "> Voir les fiches d'OpenFoodFacts !</a>
            </form>
            <div class="col-12"> <br/></div>
    </div>
</div>
<script>
    function initMap() {
  const map = new google.maps.Map(document.getElementById("gmap-window"), {
    zoom: 5,
    center: { lat: {{ gmap_average.av_lat }}, lng: {{ gmap_average.av_lng }} },
  });
  const labels = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  const markers = locations.map((location, i) => {
    return new google.maps.Marker({
      position: location,
      label: labels[i % labels.length],
    });
  });
  new MarkerClusterer(map, markers, {
    imagePath:
      "{% static 'substitute/png/m/m' %}",
  });
}
const locations = [
    {% for k, v in gmap_markers.items %}
     { lat:{{v.lat }}, lng:{{ v.lng }} },
    {% endfor %}
];
</script>
<script src="https://unpkg.com/@googlemaps/markerclustererplus/dist/index.min.js"></script>
{% endblock %}

Pure_Beurre/substitute/templates/substitute/browser.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'substitute:home' %}"><img src="{% static 'substitute/png/logo_pb_min.png' %}" alt="logo de Pur Beurre"></a>
  <a class="navbar-brand" href="{% url 'substitute:home' %}" id="version_tag"><h3> Pur Beurre </h3><h4>{{ version_tag }}</h4></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <form method="POST" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" name="browser_product" size="40" placeholder="produit " aria-label="Chercher">
      </form>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="navbar-brand" href="{% url 'substitute:login' %}">
            <input type="image" height="50" width="50" alt="Boutton - mon compte"  src="{% static 'substitute/png/green_user_sticker.png' %}" />
          </a>
        </li>
        <li class="nav-item">
        <a class="navbar-brand" href="{% url 'substitute:historic' %}"><input type="image" height="50" width="50" alt="Boutton - Mes Aliments"  src="{% static 'substitute/png/colored_carott_sticker.png' %}" /></a>
      </li>
          {% else %}
        <li class="nav-item">
          <a class="navbar-brand login" href="{% url 'substitute:login' %}">
          <input type="image" height="50" width="50" alt="Boutton - Créer mon compte"  src="{% static 'substitute/png/black_user_sticker_new.png' %}" />
        </a>
        </li>
      {% endif %}
      <li class="nav-item">
        <a class="navbar-brand logout" href="{% url 'substitute:logout' %}"><input type="image" height="50" width="50" alt="Boutton - Déconnexion"  src="{% static 'substitute/png/disconnect_sticker.png' %}" /></a>
      </li>
    </ul>
    </div>
</nav>

Pure_Beurre/substitute/templates/substitute/footer.html
{% load static %}
<footer>
    <div class="container">
        <div class="row">
            <div class="col-12"> <br/></div>
            <div class="col-12 col-md-6 h2"><a class="white-text" href="{% url 'substitute:mentions' %}"> Mentions Légales</a></div>
            <div class="col-12 col-md-6 h2"><a class="white-text" href="https://www.linkedin.com/in/stephen-a-ogolo-410ab7b0/"> Contact</a></div>
            <div class="col-12"> <br/></div>
        </div>
    </div>
</footer>

Pure_Beurre/substitute/templates/substitute/results.html
{% extends 'substitute/base.html'%}
{% block heart %}
{% load static %}
<style type="text/css">
    #searched-aliment-area
    {
        background: url('{{ product.url_image}}');
        background-position: center;
        background-size: 10%;
    }
</style>
<div class="container-fluid" id="aliment-area">
    <div class="row d-flex justify-content-center " id="searched-aliment-area">
        <div class="col-12"><br/></div>
        <div class="col-3 h1 btn btn-lg btn-create-account btn-block text-uppercase bg-butter">
            <div>{{ product.brand }} {{ product.name }}</div>
                {% if product.nutriscore == "a" %}
                <div><img src="{% static 'substitute/png/a_nutriscore_good.png' %}" alt="Photo de Colette"></div>
                {% elif product.nutriscore == "b" %}
                <div><img src="{% static 'substitute/png/b_nutriscore_good.png' %}" alt="Photo de Colette"></div>
                {% elif product.nutriscore == "c" %}
                <div><img src="{% static 'substitute/png/c_nutriscore_good.png' %}" alt="Photo de Colette"></div>
                {% elif product.nutriscore == "d" %}
                <div><img src="{% static 'substitute/png/d_nutriscore_good.png' %}" alt="Photo de Colette"></div>
                {% elif product.nutriscore == "e" %}
                <div><img src="{% static 'substitute/png/e_nutriscore_good.png' %}" alt="Photo de Colette"></div>
                {% endif %}
        </div>
        <div class="col-12"><br/></div>
    </div>
    <div class="row" style="align-items:center">
        <div class="col-12 h2" id="found-substitutes-area">Vous pouvez remplacez cet aliment par :</div>
        <div class="col-12"><br/></div>
        {% for key, value in results.items %}
        <div class="col-sm-4 col-12 h2">
            <div class="col-8 h2 border"style="margin-left:auto">
                <div class="col-12 nutriscore_tag chocolate-text border">{{ value.nutriscore }}</div>
                <div><img src="{{ value.url_image }}"></div>
                <div class="col-12 justify-content-center">
                    <div class="col-12"><br/></div>
                    <a href="{% url 'substitute:aliment' pk=key %}" class="chocolate-text " style="text-decoration:none">
                        <div class="col-12 justify-content-center font-1"> {{ value.name }} </div>
                        <div class="col-12 justify-content-center font-1"> {{ value.brand }} </div>
                    </a>
                    <div class="col-12"><br/></div>
                    <form method="POST" class="form-inline my-2 my-lg-0">
                        {% csrf_token %}
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'substitute:save' p_id=product.id s_id=key u_id=user.id %}">
                            <div class="col-6 col-md-6 h3"><img height="20" width="20" alt="Boutton - disquette"  src="{% static 'substitute/png/blue_save.png' %}"></div>
                            <div class="col-6 col-md-6 h3">Sauvegarder</div>
                        </a>
                        {% else %}
                        <a href="{% url 'substitute:login' %}">
                            <div class="col-1 col-md-1 h3">
                                <input type="image" height="20" width="20" alt="Boutton - telephone"  src="{% static 'substitute/png/blue_save.png' %}"/>
                            </div>
                            <div class="col-1 col-md-1 h3">
                                Sauvegarder
                            </div>
                        </a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Pure_Beurre/substitute/templates/substitute/search.html
{% extends 'substitute/base.html'%}
{% block heart %}
{% load static %}
<style type="text/css">
    #searched-aliment-area
    {
        background: url('{{ product.url_image}}');
        background-position: center;
        background-size: 10%;
    }
</style>
<div class="container-fluid" id="aliment-area">
    <div class="row d-flex justify-content-center " id="searched-aliment-area">
        <div class="col-12"><br/></div>
        <div class="col-sm-md-3 h1 ">
            <a class="btn btn-lg btn-create-account btn-block text-uppercase bg-butter" href="{{ product.url }}">
            <div>{{ product.brand }} {{ product.name }}</div>
                <div><img src="{{ product_nutriscore }}" alt="Nutriscore"></div>
                </a>
        </div>
        <div class="col-12"><br/></div>
    </div>
    <div class="row" style="align-items:center">
        <div class="col-12 h2" id="found-substitutes-area">Vous pouvez remplacez cet aliment par :</div>
        <div class="col-12"><br/></div>
        {% for key, value in results.items %}
        <div class="col-sm-4 col-12 h2">
            <div class="col-8 h2 border"style="margin-left:auto">
                <div class="col-12 nutriscore_tag chocolate-text border">{{ value.nutriscore }}</div>
                <div><a id="product-picture" href="{{ value.url }}"><img src="{{ value.url_image }}"></a></div>
                <div class="col-12 justify-content-center">
                    <div class="col-12"><br/></div>
                    <a href="{% url 'substitute:aliment' s_id=key p_id=product.id u_id=user.id %}" class="chocolate-text " style="text-decoration:none">
                    {% comment %}
                        <a href="{% url 'substitute:aliment' s_id=key %}" class="chocolate-text " style="text-decoration:none">
                            {% endcomment %}
                        <div class="col-12 justify-content-center font-1"> {{ value.name }}</div>
                        <div class="col-12 justify-content-center font-1"> {{ value.brand }} </div>
                    </a>
                    <div class="col-12"><br/></div>
                    <form method="POST" class="form-inline my-2 my-lg-0">
                        {% csrf_token %}
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'substitute:save' s_id=key p_id=product.id u_id=user.id %}">
                            <div class="col-6 col-md-6 h3"><img height="20" width="20" alt="Boutton - disquette"  src="{% static 'substitute/png/blue_save.png' %}"></div>
                            <div class="col-6 col-md-6 h3">Sauvegarder</div>
                        </a>
                        {% else %}
                        <a href="{% url 'substitute:login' %}">
                            <div class="col-1 col-md-1 h3">
                                <input type="image" height="20" width="20" alt="Boutton - telephone"  src="{% static 'substitute/png/blue_save.png' %}"/>
                            </div>
                            <div class="col-1 col-md-1 h3">
                                Sauvegarder
                            </div>
                        </a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="account-container">
    <div><img src="{% static 'substitute/png/remy_and_friend_sticker.png' %}" alt="Remy et son ami"></div>
</div>
{% endblock %}